-- 코드를 입력하세요
SELECT a.AUTHOR_ID, AUTHOR_NAME, CATEGORY, sum(PRICE*SALES) as TOTAL_SALES
from BOOK a, AUTHOR b, BOOK_SALES c
where a.AUTHOR_ID = b.AUTHOR_ID
and a.BOOK_ID = c.BOOK_ID
and DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-01'
group by a.AUTHOR_ID, AUTHOR_NAME, CATEGORY
order by a.AUTHOR_ID, CATEGORY desc