SELECT A.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO AS A, ITEM_TREE AS B
WHERE A.ITEM_ID = B.ITEM_ID
AND A.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID
                      FROM ITEM_TREE
                      WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY A.ITEM_ID DESC