WITH RECURSIVE GEN AS (
  -- 1세대(루트)
  SELECT ID, PARENT_ID, 1 AS GENERATION
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL

  UNION ALL

  -- 부모 세대 + 1
  SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
  FROM ECOLI_DATA E
  JOIN GEN G ON E.PARENT_ID = G.ID
)
SELECT
  COUNT(*) AS COUNT,
  G.GENERATION
FROM GEN G
LEFT JOIN ECOLI_DATA C           -- 자식 존재 여부 확인
  ON C.PARENT_ID = G.ID
WHERE C.ID IS NULL                -- 자식 없는 개체(leaf)만
GROUP BY G.GENERATION
ORDER BY G.GENERATION;
