SELECT DISTINCT A.NAME, A.DATETIME
FROM ANIMAL_INS AS A, ANIMAL_OUTS AS B
WHERE A.ANIMAL_ID NOT IN (SELECT ANIMAL_ID
                          FROM ANIMAL_OUTS AS B)
ORDER BY B.DATETIME - A.DATETIME DESC
LIMIT 3