select a.TITLE, a.BOARD_ID, 
       b.REPLY_ID, b.WRITER_ID, b.CONTENTS, DATE_FORMAT(b.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
from USED_GOODS_BOARD as a, USED_GOODS_REPLY as b
where a.BOARD_ID = b.BOARD_ID
and DATE_FORMAT(a.CREATED_DATE, "%Y-%m") = "2022-10"
order by b.CREATED_DATE, a.TITLE
