SELECT 
       CASE
            WHEN TRUNC(PRICE/10000) = 0 THEN '0'
            ELSE CONCAT(TRUNC(PRICE/10000), '0000')
       END AS PRICE_GROUP,
       COUNT(*) AS "PRODUCTS"
FROM PRODUCT
GROUP BY TRUNC(PRICE/10000)
ORDER BY PRICE_GROUP